package com.stockpro.alert.entity;

public enum AlertType {
  LOW_STOCK,
  OVERSTOCK,
  PO_PENDING,
  OVERDUE_RECEIPT,
  SYSTEM,
  SYSTEM_MAINTENANCE,
  SECURITY_ALERT,
  INVENTORY_COUNT,
  GENERAL_NOTICE
}
