spring.config.import=optional:file:.env[.properties],optional:file:services/supplier-service/.env[.properties]
spring.application.name=${APP_NAME:supplier-service}
server.port=${SERVER_PORT:8085}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JPA / Hibernate (Common config)
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Flyway — DB Migrations
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Jackson — JSON Serialization
spring.jackson.serialization.write-dates-as-timestamps=false

# Error Handling
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Startup
spring.main.banner-mode=off

# Logging
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.apache=WARN
logging.level.com.zaxxer=WARN
logging.level.org.hibernate=WARN
logging.level.com.stockpro=INFO

logging.pattern.console=%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{1}) : %msg%n
logging.file.name=logs/supplier-service.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=3

# Actuator
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=1.0.0
