# ==========================================
#  Production Profile Configuration
# ==========================================

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:false}
  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    out-of-order: false

eureka:
  instance:
    prefer-ip-address: true
