-- ============================================================
--  V1 — Initial Schema
--  auth-service / stockpro_auth database
--
--  Managed by Flyway. DO NOT edit this file after it has been
--  applied to any environment. Create a new Vx__ migration instead.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    user_id       INT            NOT NULL AUTO_INCREMENT,
    full_name     VARCHAR(150)   NOT NULL,
    email         VARCHAR(255)   NOT NULL,
    password_hash VARCHAR(255)   NOT NULL,
    phone         VARCHAR(30)    NULL,
    role          VARCHAR(10)    NOT NULL DEFAULT 'STAFF',
    department    VARCHAR(100)   NULL,
    is_active     TINYINT(1)     NOT NULL DEFAULT 1,
    created_at    DATETIME       NOT NULL,
    last_login_at DATETIME       NULL,

    CONSTRAINT pk_users        PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email  UNIQUE      (email)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
